version: '3'
services:
  frontend-angular:
    build: ./frontend
    ports:
      - "80:80"

  backend-nestjs:
    build: ./backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - network-app

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - network-app
    ports:
      - "27017:27017"

networks:
  network-app: